<tt>
I&nbsp;have&nbsp;a&nbsp;couple&nbsp;questions&nbsp;regarding&nbsp;error&nbsp;handling&nbsp;in&nbsp;HTML&nbsp;5&nbsp;workers. &lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;In&nbsp;the&nbsp;spec,&nbsp;it&nbsp;says&nbsp;&quot;Whenever&nbsp;a&nbsp;runtime&nbsp;script&nbsp;error&nbsp;occurs&nbsp;in&nbsp;one&nbsp;of&nbsp;the&nbsp;worker&#39;s&nbsp;scripts,&nbsp;if&nbsp;the&nbsp;error&nbsp;did&nbsp;not&nbsp;occur&nbsp;while&nbsp;handling&nbsp;a&nbsp;previous&nbsp;script&nbsp;error,&nbsp;the&nbsp;user&nbsp;agent&nbsp;must&nbsp;report&nbsp;the&nbsp;error&nbsp;using&nbsp;the&nbsp;WorkerGlobalScope&nbsp;object&#39;s&nbsp;onerror&nbsp;attribute.&quot;.&nbsp;Does&nbsp;it&nbsp;mean&nbsp;that&nbsp;onerror&nbsp;attribute&nbsp;of&nbsp;WorkerContext&nbsp;would&nbsp;be&nbsp;called?&nbsp;In&nbsp;addition&nbsp;to&nbsp;the&nbsp;errors&nbsp;being&nbsp;thrown?&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;The&nbsp;spec&nbsp;also&nbsp;says&nbsp;&quot;For&nbsp;dedicated&nbsp;workers,&nbsp;if&nbsp;the&nbsp;error&nbsp;is&nbsp;still&nbsp;not&nbsp;handled&nbsp;afterwards,&nbsp;or&nbsp;if&nbsp;the&nbsp;error&nbsp;occurred&nbsp;while&nbsp;handling&nbsp;a&nbsp;previous&nbsp;script&nbsp;error,&nbsp;the&nbsp;user&nbsp;agent&nbsp;must&nbsp;queue&nbsp;a&nbsp;task&nbsp;to&nbsp;fire&nbsp;a&nbsp;worker&nbsp;error&nbsp;event&nbsp;at&nbsp;the&nbsp;Worker&nbsp;object&nbsp;associated&nbsp;with&nbsp;the&nbsp;worker.&quot;.&nbsp; What&nbsp;does&nbsp;it&nbsp;mean&nbsp;by&nbsp;&quot;the&nbsp;error&nbsp;is&nbsp;still&nbsp;not&nbsp;handled&nbsp;afterwards&quot;? Does&nbsp;it&nbsp;mean&nbsp;that&nbsp;the&nbsp;onerror&nbsp;attribute&nbsp;is&nbsp;not&nbsp;set&nbsp;for&nbsp;WorkerContext?&lt;/div&gt;<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Thanks,&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Jian&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;<br>

</tt>
